sonata_admin:
    templates:
        layout:                         '@RemarkAdmin/SonataAdmin/standard_layout.html.twig'
        ajax:                           '@RemarkAdmin/SonataAdmin/ajax_layout.html.twig'
        list:                           '@RemarkAdmin/SonataAdmin/CRUD/list.html.twig'
        show:                           '@RemarkAdmin/SonataAdmin/CRUD/show.html.twig'
        show_compare:                   '@RemarkAdmin/SonataAdmin/CRUD/show_compare.html.twig'
        edit:                           '@RemarkAdmin/SonataAdmin/CRUD/edit.html.twig'
        history:                        '@RemarkAdmin/SonataAdmin/CRUD/history.html.twig'
        preview:                        '@RemarkAdmin/SonataAdmin/CRUD/preview.html.twig'
        delete:                         '@RemarkAdmin/SonataAdmin/CRUD/delete.html.twig'
        batch:                          '@RemarkAdmin/SonataAdmin/CRUD/list__batch.html.twig'
        acl:                            '@RemarkAdmin/SonataAdmin/CRUD/acl.html.twig'
        action:                         '@RemarkAdmin/SonataAdmin/CRUD/action.html.twig'
        select:                         '@RemarkAdmin/SonataAdmin/CRUD/list__select.html.twig'
        filter:                         '@RemarkAdmin/SonataAdmin/Form/filter_admin_fields.html.twig'
        dashboard:                      '@RemarkAdmin/SonataAdmin/Core/dashboard.html.twig'
        search:                         '@RemarkAdmin/SonataAdmin/Core/search.html.twig'
        batch_confirmation:             '@RemarkAdmin/SonataAdmin/CRUD/batch_confirmation.html.twig'
        inner_list_row:                 '@RemarkAdmin/SonataAdmin/CRUD/list_inner_row.html.twig'
        base_list_field:                '@RemarkAdmin/SonataAdmin/CRUD/base_list_field.html.twig'
        list_block:                     '@RemarkAdmin/SonataAdmin/Block/block_admin_list.html.twig'
        user_block:                     '@RemarkAdmin/SonataAdmin/Core/user_block.html.twig'
        add_block:                      '@RemarkAdmin/SonataAdmin/Core/add_block.html.twig'
        pager_links:                    '@RemarkAdmin/SonataAdmin/Pager/links.html.twig'
        pager_results:                  '@RemarkAdmin/SonataAdmin/Pager/results.html.twig'
        tab_menu_template:              '@RemarkAdmin/SonataAdmin/Core/tab_menu_template.html.twig'
        history_revision_timestamp:     '@RemarkAdmin/SonataAdmin/CRUD/history_revision_timestamp.html.twig'
        short_object_description:       '@RemarkAdmin/SonataAdmin/Helper/short-object-description.html.twig'
        search_result_block:            '@RemarkAdmin/SonataAdmin/Block/block_search_result.html.twig'
        action_create:                  '@RemarkAdmin/SonataAdmin/CRUD/dashboard__action_create.html.twig'
        button_acl:                     '@RemarkAdmin/SonataAdmin/Button/acl_button.html.twig'
        button_create:                  '@RemarkAdmin/SonataAdmin/Button/create_button.html.twig'
        button_edit:                    '@RemarkAdmin/SonataAdmin/Button/edit_button.html.twig'
        button_history:                 '@RemarkAdmin/SonataAdmin/Button/history_button.html.twig'
        button_list:                    '@RemarkAdmin/SonataAdmin/Button/list_button.html.twig'
        button_show:                    '@RemarkAdmin/SonataAdmin/Button/show_button.html.twig'
