imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Sonataadmin Configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        # ...
sonata_admin:
    templates:
        layout:                         RemarkAdminBundle::standard_layout.html.twig
        ajax:                           RemarkAdminBundle::ajax_layout.html.twig
        list:                           RemarkAdminBundle:CRUD:list.html.twig
        show:                           RemarkAdminBundle:CRUD:show.html.twig
        show_compare:                   RemarkAdminBundle:CRUD:show_compare.html.twig
        edit:                           RemarkAdminBundle:CRUD:edit.html.twig
        history:                        RemarkAdminBundle:CRUD:history.html.twig
        preview:                        RemarkAdminBundle:CRUD:preview.html.twig
        delete:                         RemarkAdminBundle:CRUD:delete.html.twig
        batch:                          RemarkAdminBundle:CRUD:list__batch.html.twig
        acl:                            RemarkAdminBundle:CRUD:acl.html.twig
        action:                         RemarkAdminBundle:CRUD:action.html.twig
        select:                         RemarkAdminBundle:CRUD:list__select.html.twig
        filter:                         RemarkAdminBundle:Form:filter_admin_fields.html.twig
        dashboard:                      RemarkAdminBundle:Core:dashboard.html.twig
        search:                         RemarkAdminBundle:Core:search.html.twig
        batch_confirmation:             RemarkAdminBundle:CRUD:batch_confirmation.html.twig
        inner_list_row:                 RemarkAdminBundle:CRUD:list_inner_row.html.twig
        base_list_field:                RemarkAdminBundle:CRUD:base_list_field.html.twig
        list_block:                     RemarkAdminBundle:Block:block_admin_list.html.twig
        user_block:                     RemarkAdminBundle:Core:user_block.html.twig
        add_block:                      RemarkAdminBundle:Core:add_block.html.twig
        pager_links:                    RemarkAdminBundle:Pager:links.html.twig
        pager_results:                  RemarkAdminBundle:Pager:results.html.twig
        tab_menu_template:              RemarkAdminBundle:Core:tab_menu_template.html.twig
        history_revision_timestamp:     RemarkAdminBundle:CRUD:history_revision_timestamp.html.twig
        short_object_description:       RemarkAdminBundle:Helper:short-object-description.html.twig
        search_result_block:            RemarkAdminBundle:Block:block_search_result.html.twig
        action_create:                  RemarkAdminBundle:CRUD:dashboard__action_create.html.twig
        button_acl:                     RemarkAdminBundle:Button:acl_button.html.twig
        button_create:                  RemarkAdminBundle:Button:create_button.html.twig
        button_edit:                    RemarkAdminBundle:Button:edit_button.html.twig
        button_history:                 RemarkAdminBundle:Button:history_button.html.twig
        button_list:                    RemarkAdminBundle:Button:list_button.html.twig
        button_show:                    RemarkAdminBundle:Button:show_button.html.twig